### ISSUE TITLE
Two Module Missing in setup.sh & A Little Mistake in README.md

### ISSUE THREAD

**Issue by AllenZ01** [TimeLovercc/CAF-GNN#1]
Hi, thanks for the great work ! Yet two issues occur when I'm reproducing it.
### 1. Two Module Missing in setup.sh
To run the code, Module **Pandas** and **Rich** are also needed. However they are not in the setup.sh
### 2. A Little Mistake in README.md
in [this line](https://github.com/TimeLovercc/CAF-GNN/blob/82819b458bafa7d179e70789cf3610102b6e52ef/README.md?plain=1#L67) the dataset_name should be 'bail' since the line above say so.

Thanks again for the great work !

**Comment by TimeLovercc** [comment]
Thank you so much for pointting out the issues! I have updated the code.
