### ISSUE TITLE
Some Issues in Data Processing Modules

### ISSUE THREAD

**Issue by AllenZ01** [TimeLovercc/CAF-GNN#2]
Hi, I notice some issues in all three files './src/datasets/**bail.py**&**credit.py**&**german.py**'.
Take '**bail.py**' as an example:

1. [Line13](https://github.com/TimeLovercc/CAF-GNN/blob/main/src/datasets/bail.py#L13) `self.load(self.processed_paths[0])` 
Maybe you mean `self.data = torch.load(self.processed_paths[0])[0]`?

2. [Line14](https://github.com/TimeLovercc/CAF-GNN/blob/main/src/datasets/bail.py#L14) `sens_idx = 1`
I think the `sens_idx` for `bail` is supposed to be `0`.

3. [Line15](https://github.com/TimeLovercc/CAF-GNN/blob/main/src/datasets/bail.py#L15) `self.data.x[:, sens_idx] = self.data.sens`
I don't understand what this line does, since `self.data.x[:, sens_idx]` always equals to `self.data.sens`

4. [Line31](https://github.com/TimeLovercc/CAF-GNN/blob/main/src/datasets/bail.py#L31) `self.save([data], self.processed_paths[0])`
Maybe you mean `torch.save([data], self.processed_paths[0])`?

**Comment by TimeLovercc** [comment]
Thank you so much for your issues. 

For the first question and fourth question, the code is correct. I just use the methods in parent class. You can check the code of `in_memory_dataset` [here](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/data/in_memory_dataset.html#InMemoryDataset) to find the `load` method and `save` method.

For the second question, you are correct. I have updated the code based on the `sens_idx` in nifty [code](https://github.com/chirag126/nifty/blob/main/nifty_sota_gnn.py).

For the third question, in the processing part we may do some normalization or transformations for the `x`. But we don't wan t to affect the sensitive attribute. Thus, we have a manual operation here to give the sensitive attribute in the feature matrix the original value, which is stored in `self.data.sens`.

I'm really grateful for your careful checking and all the questions. After I rewrote my code in pytorch lightning, I do not have time to review the code carefully. Your comments are really helpful. If you have any questions, please feel free to open more issues.

**Comment by AllenZ01** [comment]
Hi, thanks for the quick reply. 
You are right about Q1,3&4. The reason why I didn't find `save` & `load` method in `InMemoryDataset` is that I installed `torch_geometric==2.0.2` (due to some GPU driver limitations), not `2.3.1` as requested. In `torch_geometric==2.0.2`, `InMemoryDataset` doesn't have `save` & `load` method.
Anyway, thanks for addressing my issures so clearly!
