### ISSUE TITLE
Doubts about normalize in conv

### ISSUE THREAD

**Issue by Yun-Fu** [TimeLovercc/CAF-GNN#6]
https://github.com/TimeLovercc/CAF-GNN/blob/d0db98f7386b668e34105498f4addf6306f2fa69/src/models/caf.py#L19
Hi, thanks for the great work ! But I still have some doubts about the normalize operation in the code. Can you tell me why the conv of each layer of the encoder needs to perform an additional normalize operation? What is the purpose of doing this? Thank you very much for your reply

**Comment by TimeLovercc** [comment]
Thank you for asking. A simple explanation is that I find that NIFTY use this SAGE design and I want to make our base model consistent. You can find the code of NIFTY SAGE implementation: https://github.com/chirag126/nifty/blob/main/models/sage.py
